#!/bin/bash

# Install required packages
yum install -y yum-utils
yum install -y device-mapper-persistent-data
yum install -y lvm2

# Add docker repo
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

# Install docker
yum install -y docker-ce
yum install -y docker-ce-cli

# Setup Docker Environement... (1/3)
mkdir -p /etc/docker
chmod 0755 /etc/docker

# Setup Docker Environement... (2/3)
mkdir -p /etc/systemd/system/docker.service.d
chmod 0755 /etc/systemd/system/docker.service.d

# Setup Docker Environment... (3/3)
systemctl daemon-reload
systemctl enable docker
systemctl restart docker
