#!/bin/bash

# check if base installation is required
if ["$DIB_CUSTOM_KUBERNETES" != ""]
then
  exit 0;
fi

# Adding K8s repo...
cat > /etc/yum.repos.d/kubernetes.repo <<EOF
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF

# Installing K8s client packages...
export PACKAGES=(
    "kubelet-1.14.1"
    "kubectl-1.14.1"
    "kubeadm-1.14.1"
)

for PACKAGE in ${PACKAGES[*]}
do
    yum install -y "$PACKAGE"
done


# Pull K8s images...
export IMAGES=(
    "k8s.gcr.io/kube-proxy:v1.14.1"
    "k8s.gcr.io/pause:3.1"
    "k8s.gcr.io/etcd:3.3.10"
    "k8s.gcr.io/coredns:1.3.1"
    "k8s.gcr.io/kube-apiserver:v1.14.1"
    "k8s.gcr.io/kube-controller-manager:v1.14.1"
    "k8s.gcr.io/kube-scheduler:v1.14.1"
)

for IMAGE in ${IMAGES[*]}
do
    docker pull "$IMAGE"
done

# Setup K8s environment...
systemctl stop firewalld
systemctl enable kubelet.service
