#!/bin/bash

# check if chart registry installation is required
if ["$DIB_CUSTOM_CHART_REGISTRY" != ""]
then
  exit 0;
fi

# create chartmuseumm repo directory
mkdir -p /opt/chartmuseum/charts
chmod 777 -R /opt/chartmuseum/charts

# create start script for chartmuseum
cat > /usr/local/bin/start_chartmuseum.sh <<EOF
docker stop chartmuseum
docker rm chartmuseum
docker pull chartmuseum/chartmuseum
docker run -dit -p 8080:8080  -v /opt/chartmuseum/charts:/charts -e DEBUG=true -e STORAGE=local -e STORAGE_LOCAL_ROOTDIR=/charts --name chartmuseum --restart always chartmuseum/chartmuseum
EOF
chmod a+x /usr/local/bin/start_chartmuseum.sh

# create stop script for chartmuseum
cat > /usr/local/bin/stop_chartmuseum.sh <<EOF
docker stop chartmuseum
docker rm chartmuseum
EOF
chmod a+x /usr/local/bin/stop_chartmuseum.sh

# install helm v3
cd /tmp
curl https://get.helm.sh/helm-v3.0.0-rc.3-linux-amd64.tar.gz > /tmp/helm-v3.0.0-rc.3-linux-amd64.tar.gz
tar xvf /tmphelm-v3.0.0-rc.3-linux-amd64.tar.gz
cp /tmp/linux-amd64/helm /usr/local/bin/helm
chmod a+x /usr/local/bin/helm
