#!/bin/bash

# check if diskimage-builder installation is required
if ["$DIB_CUSTOM_BUILDER" != ""]
then
  exit 0;
fi

# create setup script to create diskimage-builder image
cat /usr/local/bin/setup_builder.sh <<EOF
# check if the image has already been built
if [[ "$(docker images -q tsai/diskimage-builder 2> /dev/null)" == "" ]]; then
  # clone repo into /opt/diskimage-builder
  cd /opt
  rm -rf diskimage-builder
  git clone https://github.com/BernardTsai/diskimage-builder.git

  # move to the docker subdirectory and build the image
  cd docker
  ./build_diskimage_builder_container.sh
fi
EOF
chmod a+x /usr/local/bin/setup_builder.sh 
